stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Starting building the app"
    - npm install
    - npm run build
    - echo "Build successful"

# --- Below is commented because there are no tests to run.
# test:
#  stage: test
#  image: node
#  script:
#    - echo "Testing app"
#    - npm install
#    - CI=true npm test
#    - echo "Test successful"
